version: '3.8'

services:
  fishjam:
    image: ghcr.io/fishjam-dev/fishjam:0.6.2
    ports:
      - "5002:5002"
      - "50000-50050:50000-50050/udp"
    environment:
      - FJ_CHECK_ORIGIN=false
      - FJ_HOST=${LAN_IP:-127.0.0.1}:5002
      - FJ_PORT=5002
      - FJ_WEBRTC_USED=true
      - FJ_WEBRTC_TURN_PORT_RANGE=50000-50050
      - FJ_WEBRTC_TURN_LISTEN_IP=0.0.0.0
      - FJ_WEBRTC_TURN_IP=${LAN_IP:-127.0.0.1}
      - FJ_SERVER_API_TOKEN=development
